### ISSUE TITLE
GitHub API: User Names

### ISSUE THREAD

**Issue by LelandCurtis** [LelandCurtis/little-esty-shop#3]
As a visitor or an admin user
When I visit any page on the site
I see the Github usernames of myself and my teammates somewhere on the site
The most up to date usernames are always displayed

**Comment by EMielke76** [comment]
Could be this...[GitHub API Endpoint: Repo Contributors](https://docs.github.com/en/rest/reference/repos#list-repository-contributors)

**Comment by EMielke76** [comment]
Or this...[GitHub API Endpoint: User](https://docs.github.com/en/rest/reference/users#get-a-user)
